### ISSUE TITLE
just: vpn shortcuts

### ISSUE THREAD

**Issue by castrojo** [ublue-os/config#105]
VPNs usually need to be layered, we should just do like:

    just vpn-nord
    just vpn-express

And so on and then automate that for people.

**Comment by noelmiller** [comment]
I have concerns about the scope for this. I already thought of a few more VPN providers that we could put into this list, but that increases the maintenance burden on us. 

I'm wondering if it would better suit us to write a guide on how to install a VPN by layering an RPM file the VPN company provides to you rather than trying to support an arbitrary amount of VPN providers.

I don't think this would be terribly hard to implement, I just want to have reasonable guardrails around it.
