### ISSUE TITLE
just: automate setting up RHEL containers

### ISSUE THREAD

**Issue by castrojo** [ublue-os/config#106]
It should be easy for people who work with RHEL to use our stuff. Looks like what we need is documented here: 

https://debarshiray.wordpress.com/2023/08/25/fedora-meets-rhel-upgrading-ubi-to-rhel/

It'd be neat to set it up exactly how they want it with toolbx too, let's not make editorial decisions on their preferred tools.

**Comment by bsherman** [comment]
Sounds like this is simply adding a `just` directive (or set of them) which would do this: `toolbox create --distro rhel --release 9.2` maybe with parameter... and ideally using distrobox....

But... maybe this would also be a reason to stop removing `toolbox`, too... RHEL users may really want it as a fallback for their use case.

**Comment by noelmiller** [comment]
# My Head Hurts
So, the landscape is confusing in regards to Red Hat Toolbox Containers. I'm going to ask some questions tomorrow to hopefully get a better understanding of what customers and individuals should be using.

# UBI
Images are available to use completely for free and can be accessed from `registry.access.redhat.com` without a subscription. The FAQ clearly indicates that anyone can use these images. https://developers.redhat.com/articles/ubi-faq#

# quay.io RHEL toolbox images
Timothy has been managing these and they seem to be mostly up to date. They are slightly behind the official toolboxes which I will get to next. These exist here: https://quay.io/repository/toolbx-images/rhel-toolbox?tab=info

# Official Toolboxes
These require a subscription since they are hosted at `registry.redhat.io` This would require you to be a customer (or maybe a developer account can access these?) These seem to be the most up to date with current RHEL releases and are specifically designed to work inside of Toolbox. 

## RHEL 8 
https://catalog.redhat.com/software/containers/rhel8/toolbox/611bd18eeb34b73652492a75?architecture=amd64&image=6543c1d79fc22886ccc4df72&container-tabs=overview

## RHEL 9: 
https://catalog.redhat.com/software/containers/rhel9/toolbox/61532be3bc74e0be7ca66e40?architecture=amd64&image=6571634acb7b2ef3e5ae8937&container-tabs=overview

# Other Toolbox Images
From the offical [toolbox repo](https://github.com/containers/toolbox) there are several out of date containers there for RHEL: https://github.com/containers/toolbox/tree/main/images/rhel

# Conclusion
My gut tells me we should use the official toolbox images from `registry.redhat.io`, but this will require the user to log into the registry in order to pull the images. This also offers more options since every minor release is available in case they don't want just `:latest`. 

However, if we think just having one for `rhel-ubi8` and `rhel-ubi9` would be good, I can add those as separate ones and those shouldn't require a login.

**Comment by bsherman** [comment]
I want to clarify that I assumed the use of `distrobox` in my earlier comment, but then re-read (and I think discussed with @castrojo) and I believe we'd expected `toolbox` to be used for these RHEL `*boxes`.
