### ISSUE TITLE
Investigate flatpak update maintenance

### ISSUE THREAD

**Issue by castrojo** [ublue-os/config#14]
Not sure if we need to do an automated `flatpak repair` and or remove unusued, and update appstream, etc. We should make sure we're making it so users don't need to "remember" to do any kind of maintenance.

**Comment by bsherman** [comment]
#26 addresses potential improvements to flatpak updates... probably could be in same service or one related to `flatpak repair`

**Comment by fiftydinar** [comment]
If Gnome Software is used regurarly in Ublue by its users, it already handles automatic removing of unused depedencies when you uninstall an app. They recently added support for it, along with an option to delete all data when uninstalling an app for clean uninstallation.

For other platforms like KDE Discover, I'm not sure.

So that should also be taken in mind when designing such a solution.
Being careful between dividing GUI Software functionality & Ublue CLI flatpak maintaining functionality.

**Comment by bsherman** [comment]
I've tinkered with `flatpak repair` a bit... 

If we want this, I'd suggest it be a weekly operation, not daily, and be sibling services/timers to `flatpak-user-update` `flatpak-system-update`.

I'm unsure if there is any downside (other than cpu/memory/disk-iops usage) to doing this ... if so it's an easy win, but we should model the services/timers after the outcome of #26

**Comment by un1c3** [comment]
I think `flatpak update` also updates the appstream so I don't think it is necessary to address this.

For `flatpak uninstall --unused` and `flatpak repair`, could this be achieved using the `ExecStartPre=` and `ExecStartPost=` directives respectively?

The execution plan for the services would then be,

1. Uninstall all unused packages and runtimes.

1. Update all flatpaks installed.

1. Repair any broken flatpak installations.

**Comment by bsherman** [comment]
> For `flatpak uninstall --unused` and `flatpak repair`, can I suggest using the `ExecStartPre=` and `ExecStartPost=` directives respectively?

I like this suggestion. I was not excited about adding another service.
