### ISSUE TITLE
use `just` includes functionality once stable

### ISSUE THREAD

**Issue by castrojo** [ublue-os/config#16]
We should add a shortcut that lets people get the latest templated updates from us but backs up their existing ~/.justfile -- that way people can keep their modifications but still get all the convenience stuff we're putting in.

**Comment by EinoHR** [comment]
We should really *just* use just includes (https://just.systems/man/en/chapter_52.html) instead of copying the justfile. This is currently `--unstable`, so we'd probably rather wait for a future release of just to add this. This would also mean that the updates from the ublue justfile would be automatically available on users computers.

**Comment by castrojo** [comment]
Agreed! Let's do it that way!

**Comment by bsherman** [comment]
do we want to rename this to "use just's include feature" now?  

And when that feature is no longer unstable, it'll probably only need us to change [profile.d/ublue-os-just.sh]( https://github.com/ublue-os/config/blob/main/build/ublue-os-just/ublue-os-just.sh) now that we've made other modifications.

**Comment by bsherman** [comment]
#61  is related to this...

and #49 pretty much short-circuited this issue...

but between the two of them, we can probably close this, unless we want to keep it open until we don't need the `--unstable` any longer.
