### ISSUE TITLE
provide option to use toolbox in our distrobox just recipes

### ISSUE THREAD

**Issue by bsherman** [ublue-os/config#186]
I suggest maybe add an argument to all our distrobox recipes which allows toggling toolbox, and perhaps allows setting an env var which defaults to toolbox. The idea people that some users definitely do use it exclusively.

> Giving users a choice definitely is better in my opinion (but I think we should default to distrobox). 

I agree, mostly from the position that our just recipes are all, already `distrobox-*` 

>Is it possible to import variable files into justfiles? That way, we could define all of our containers we want to use and make them available to both toolbox and distrobox.

Yes. This latter thought is basically what I was suggesting in my second option... 

I'd be happy to merge [this](https://github.com/ublue-os/config/pull/185) as is, but file a follow-up issue to be more "toolbox-friendly" and either coach you through the env var stuff or provide the PR myself.

_Originally posted by @bsherman in https://github.com/ublue-os/config/issues/185#issuecomment-1883388950_

**Comment by bsherman** [comment]
Relates to #106

**Comment by HikariKnight** [comment]
when i get to reorging the distrobox just file, i want to make it possible to select image, set a name (using a just arg) and platform (distrobox or toolbox) as part of the overhaul, but since this would require some more work than the rest of the reorg, i decided to split reorging the distrobox just file as its own PR afterwards. 😃

**Comment by bsherman** [comment]
@HikariKnight this relates to your comment here: https://github.com/ublue-os/config/pull/181#issuecomment-1884266421

Even though you are on the discussion already, linking it for reference.

**Comment by HikariKnight** [comment]
Just updating that i am laying the groundwork for this now in https://github.com/ublue-os/config/pull/194
However i am not sure if everything that has a docker image has a toolbox image and UBI image so it would be nice to figure out the logic before putting it together.

**Comment by bsherman** [comment]
It was discussed and determined that neither #194 nor #199 either addressed nor hindered this issue.

Also, an important point was raised, this issue is really about enabling `toolbox` for rhel and basic fedora toolboxes, not generically attempting to support all our various distroboxes with `toolbox` as that can't work given different feature sets.

**Comment by HikariKnight** [comment]
Should we try make the just recipe work similar to `ujust distrobox-assemble` where it reads from a simplified .ini manifest and generates a list of images from that.
I am thinking something like
```ini
[rhel-ubi8]
image=registry.access.redhat.com/ubi8/toolbox:latest
distro=
release=

[rhel9]
image=
distro=rhel
release=9
```

the part inside `[]` can be used as the container name similar to how `distrobox assemble` works or we could prompt for a container name because toolbox does not have actual `assemble` functionality.
I do not really want to write an ini parser for bash, but it might be possible or we could say all the keys are required.

Then just do, if `image` is empty it will use the `distro` and `release` keys.
Thoughts?

**Comment by noelmiller** [comment]
This issue is tangentially related to this one: https://github.com/ublue-os/config/issues/210

**Comment by HikariKnight** [comment]
Regarding my previous comment, we can make assemble only use the `image` key as i made the `Toolbox` command have an abstraction to decide if the image provided is a registry or not by just checking if it contains `/`
![image](https://github.com/ublue-os/config/assets/2557889/de74c2b3-79f5-4dbf-8979-c39fbdfa7e39)

This simplifies the assemble file a lot into
```ini
[rhel-ubi8]
image=registry.access.redhat.com/ubi8/toolbox:latest

[rhel9]
image=rhel:9
```

**Comment by HikariKnight** [comment]
@bsherman @noelmiller should we use `/etc/toolbox` as the location for our assemble files for toolbox?

**Comment by castrojo** [comment]
Closing for now since there's not much energy in trying to make toolbox work for our use cases.

**Comment by bsherman** [comment]
Actually @HikariKnight pretty much implemented this.

**Comment by HikariKnight** [comment]
yep `ujust toolbox-assemble` and `ujust toolbox-new`

the assemble one is mostly a copy+paste of the "make a list of images and select one" from the `ujust assemble` for distrobox (since it was an easy way to have a standard way to provide a list of toolboxes using the same format as `distrobox.ini` but with the only option being what image to use)
so the only thing we update is the manifest file pointing to the rhel toolbox images. :)
