### ISSUE TITLE
Toolbox Distrobox Incompatabilities

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/config#210]
When a distrobox is created, it shows up in the list of Toolbox Containers that you can use. This is an issue because you receive the message below:
```
nomiller@mirkwood:~$ toolbox enter alma 
Error: container alma is too old and no longer supported 
Recreate it with Toolbox version 0.0.17 or newer.
```

We need to find a solution either in Distrobox or Toolbox and contribute that way. Otherwise, we can patch our toolbox RPM to fix this issue if we cannot find a solution upstream.

**Comment by bsherman** [comment]
I'm tinkering with some way to patch `toolbox` such that it filters out "toolbox" containers which were not created by it.

I think it's too specific for toolbox to have awareness of distrobox, but there are other ways to filter.

**Comment by m2Giles** [comment]
It's looking for the label "com.github.containers.toolbox"

If it's set at all, even to none. It will show up in the toolbox list. The only way around this was not building the container with that label.

Distrobox on the other hand is looking for the following:

distrobox in the mounts section
distrobox in the labels section

Distrobox will see our toolboxes since we have distrobox in the label usage even when used as quadlet with no mounts.

I tried removing both and now the container will show up in prompt as a regular podman container. However, it won't use the same scarf and will not properly enter if it cannot determine if it's a toolbox or distrobox.

**Comment by bsherman** [comment]
> The only way around this was not building the container with that label.

Clarification, not building the IMAGE with the label.

**Comment by bsherman** [comment]
This isn't actually completed as the problem described still exists. 

With consensus, I think we could close as "won't fix" since it's really something for toolbox/distrobox to sort out, not us.

**Comment by HikariKnight** [comment]
i agree, it is not really our job to fix this
