### ISSUE TITLE
Why put systemd services in /usr and not in /etc ?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [ublue-os/config#22]
/etc is preferred over /usr. Users can enable and disable ro services, but not modify them.

But why use /usr at all? It is read-only so users can't change it. I think OSTree systems should let users change as much as reasonably possible, and it should be discussed what really is a "core functionality"

**Comment by SimonWoodtli** [comment]
I think it has to do with ostree overwriting /etc with defaults when you rebase an image, @akdev1l just told me yesterday.

https://blog.verbum.org/2014/01/24/why-ostree-requires-usretc/

**Comment by akdev1l** [comment]
If you want to override any services deployed with the system you can do that by putting files in /etc 

Eg https://www.flatcar.org/docs/latest/setup/systemd/drop-in-units/

**Comment by trytomakeyouprivate** [comment]
@akdev1l Yes I kinda knew that, but I am wondering why use this location at all. Is it some kind of security measurement?

**Comment by castrojo** [comment]
In the past we've put stuff in `/etc` but we've found that it's nice to keep an ro set in `/usr` so that if the user wants changes they can override in `/etc` but always have a working set of stuff on the image. 

Also in this role we're kind of the distro it should all be in `/usr` anyway, though we're totally not consistently doing this right now (and we probably should be).

**Comment by trytomakeyouprivate** [comment]
@castrojo that makes sense. So okay the user can override it, thats true. Also systemd services need to be in /etc anyways to be activated.
