### ISSUE TITLE
Do not use OnBootSec in the .timer file for updates since OnCalendar is already defined

### ISSUE THREAD

**Issue by un1c3** [ublue-os/config#26]
The next run for the OnCalendar timer is calculated when the timer is first installed and is unaffected by previous runs triggered by the OnBootSec timer.

With the current implementation, if I reboot my computer at 05:50, the update service will be executed at 05:55 triggered by by the OnBootSec timer. It will then be executed again at 06:00, triggered by the OnCalendar timer. The previous run that was triggered by bootup will not affect the next run that happens at 06:00.

If your intent was to introduce a delay before the service is started, a better approach would be to use `ExecStartPre=/usr/bin/sleep 300` in the .service file.

If this is the intended behaviour, let me know and I will close the issue.

**Comment by castrojo** [comment]
I've been carrying the flatpak ones at least for a while without any real thorough review. My service unit knowledge is out of date and could use some peer review with how we're doing it. 

The intended behavior is for the flatpaks to update on a reasonable schedule without bothering the user, should we just keep the OnCalendar and not bother with the OnBootSec?

**Comment by un1c3** [comment]
If you remove the OnBootSec instructions and keep the OnCalendar instruction, the service will trigger on hours that are multiple of 6 (0000, 0600, 1200, 1800). I think you should remove the OnBootSec instruction.

**Comment by EyeCantCU** [comment]
I agree with that. Both Flatpak and rpm-ostree should update at the same time cohesively. I think running updates sometime at night and again later if the updates failed would be the best approach

Having Flatpaks update 4 times a day isn't really necessary and the fact that rpm-ostree just outright fails without retrying isn't really acceptable

So, I think our aim here should be to adjust the current update policy for Flatpaks and rpm-ostree so that they run at 4 in the morning (keeping TZ in mind) and retry later on failure

**Comment by un1c3** [comment]
@bsherman 

> Whatever we want, we should do it for rpm-ostree updates as well as flatpak so they behave in a similar manner.

> If we do this consistently for all 3 units... then we can provide simple instructions for users how to change the behavior, either to disable or change schedule, etc.

I think a simpler solution is to use a single `foo.timer` which actives `foo.service`. `foo.service` would then start `flatpak-system-update.service`, `flatpak-user-update.service`, and `rpm-ostreed-automatic.service`; which can be accomplished by adding `Wants=`flatpak-system-update.service flatpak-user-update.service rpm-ostreed-automatic.service` directive to `foo.service` and `After=foo.service` directive to the other three. So all three services start when a single timer is reached. [[systemd.service]](https://www.man7.org/linux/man-pages/man5/systemd.service.5.html#AUTOMATIC_DEPENDENCIES)

The three services could also be run one after the other and only after the previous has executed to completion using the `After=` and `Type=oneshot` directives.

> nightly updates at 4am (should respect system timezone setting)

> if an update is missed due to power off or sleep, immediately run on boot or when next available

Both of these are the default behaviour for timer units so no change would be required. If the timer is reached when the computer is turned off, the timer activates upon the next boot.

@EyeCantCU 

> the fact that rpm-ostree just outright fails without retrying isn't really acceptable

I think adding a `Restart=on-failure` directive would address this. The service should be restarted any time rpm-ostree exits with a non-zero status.

**Comment by bsherman** [comment]
I appreciate the feedback @un1c3 !

I very much like the suggestion of a single timer and using simple service dependencies to run the three services.

I feel a bit hesitant to modify `rpm-ostreed-automatic.service` or trigger it from a different timer than the default rpm-ostreed-automatic.timer`, but since the timer is not enabled by default, that could be fine.

I'm going to tinker with an implementation based on these suggestions, as I do think we need this cleaned up.

**Comment by bsherman** [comment]
Well, I don't think the idea works for `flatpak-user-update.service` to be Wanted by a `foo.service` since the former is a `--user` service.

Additionally, we already have these 3 distinct timers so I'm inclined to keep them rather than removing the 2 flatpak timers, only to add a new service and timer, while leaving the Fedora default `rpm-ostreed-automatic.timer` as disabled.

It also adds complexity. 

I'll have a PR shortly with a simple implementation of what @EyeCantCU and I had already discussed and incorporate the restart on failure suggestion.

**Comment by bsherman** [comment]
In the end, I didn't change the  rpm-ostreed-automatic.service behavior by adding `Restart=on-failure`.  realistically, this is a daily update. if it fails, it seems fine to try the next day rather than retrying several times in rapid succession. 

Overall the solution as presented in the linked PR strives to achieve the goal in the simplest possible manner.
