### ISSUE TITLE
`[: -q: binary operator expected` bug in /etc/profile.d/ublue-os-just.sh ???

### ISSUE THREAD

**Issue by bsherman** [ublue-os/config#47]
I'm putting this here so I don't forget, but i'm seeing the following on a new nvidia install:

```
[user@fedora ~] $ sudo su -
-- snip --
-bash: [: -q: binary operator expected
[root@fedora ~] #
```

I want to test and rule out any problems with that script

**Comment by un1c3** [comment]
I browsed to that point in history and this error was caused by the `[ rpm -q ublue-os-nvidia-addons ]` test condition because you didn't use command substitution.

The correct syntax would be:

```
[ $(rpm -q ublue-os-nvidia-addons) ] 2> /dev/null
```

This has to do with how test conditions work in bash. `test` exits with a 0 exit code if the condition is true and non-zero if the condition is false. `if` considers the statement to be true if the exit code for the test condition 0 and false if the exit code is non-zero.

`rpm -q ublue-os-nvidia-addons` returns a 0 or non-zero exit code depending on whether the package is installed or not. The `test` condition takes this exit code and in turn exits with a 0 or non-zero exit code based on whatever `rpm` exited with.  `2> /dev/null` gets rid of the stderr of the `test` condition.

For this to work, you have to use the `[` shell builtin; which is the same as the `test` builtin [[test]](https://www.man7.org/linux/man-pages/man1/test.1.html). You also cannot use the `[[` keyword or put the command substitution inside double quotes à la `[ "$(rpm -q ublue-os-nvidia-addons)" ]` since that prevents word splitting and makes the test condition true every time.

**Comment by bsherman** [comment]
> I browsed to that point in history and this error was caused by the `[ rpm -q ublue-os-nvidia-addons ]` test condition

Thank you for checking on this!  Sounds like a subsequent change removed that bug so we can close this.
